listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
no-loopback-peers
no-multicast-peers

# Replace HB_TURN_USER / HB_TURN_PASS in docker-compose env when starting.
user=${HB_TURN_USER}:${HB_TURN_PASS}
realm=heartbeat
log-file=stdout
syslog
